services:

  database:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
     - "${DB_PORT:-5432}:5432"
    networks:
      - default

  backend:
    restart: always
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    build:
      context: ./backend
    ports:
      - "8000:8000"
  
  frontend:
    image: node:20
    restart: always
    networks:
      - default
    build:
      context: ./frontend
    ports:
      - "5173:5173"
  
volumes:
  database-data:

networks:
  default:
